import { copyFile, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const videoDir = path.resolve(scriptDir, '..');
const gameDir = path.resolve(videoDir, '..');
const generatedDir = path.join(videoDir, 'public', 'generated');
const captureDir = path.join(generatedDir, 'capture');
const videoFiles = (await readdir(path.join(captureDir, 'videos'))).filter((file) =>
  file.endsWith('.webm')
);

if (videoFiles.length !== 1) {
  throw new Error(`Expected one captured WebM, found ${videoFiles.length}`);
}

await mkdir(path.join(generatedDir, 'fonts'), { recursive: true });
await copyFile(
  path.join(captureDir, 'videos', videoFiles[0]),
  path.join(generatedDir, 'gameplay.webm')
);
await copyFile(
  path.join(captureDir, 'screenshots', '00-opening.png'),
  path.join(generatedDir, 'opening.png')
);
await copyFile(
  path.join(captureDir, 'screenshots', '99-summit.png'),
  path.join(generatedDir, 'summit.png')
);

for (const font of [
  'shippori-mincho-700.woff2',
  'zen-maru-gothic-400.woff2',
  'zen-maru-gothic-700.woff2',
]) {
  await copyFile(
    path.join(gameDir, 'src', 'client', 'assets', 'fonts', font),
    path.join(generatedDir, 'fonts', font)
  );
}

const report = JSON.parse(
  await readFile(path.join(captureDir, 'playthrough.json'), 'utf8')
);
const events = report.events ?? [];
const readyAt = seconds(firstEvent(events, 'ready')?.at ?? 0);
const fallAt = seconds(firstEvent(events, 'fall')?.at ?? readyAt + 2);
const summitAt = seconds(firstEvent(events, 'summit')?.at ?? report.elapsedMs);
const zoneTimes = uniqueZoneTimes(events).map((entry) => seconds(entry.at));
const totalSourceSeconds = Math.max(seconds(report.elapsedMs), summitAt + 1);

const durations = [3.2, 2.8, 3, 3, 3.5, 3.5, 3, 4, 3.5, 4.5, 4, 4, 2.3, 2.3, 2.4, 2.5, 2.5];
const anchors = [
  readyAt - 0.25,
  (zoneTimes[0] ?? 13.5) - 3.2,
  (zoneTimes[0] ?? 13.5) + 0.15,
  (zoneTimes[1] ?? 27) + 0.2,
  readyAt + 0.05,
  (zoneTimes[2] ?? totalSourceSeconds * 0.25) + 0.15,
  (zoneTimes[3] ?? totalSourceSeconds * 0.33) - 0.85,
  (zoneTimes[4] ?? totalSourceSeconds * 0.42) - 0.35,
  (zoneTimes[5] ?? totalSourceSeconds * 0.5) - 0.5,
  (zoneTimes[6] ?? totalSourceSeconds * 0.58) - 0.75,
  (zoneTimes[7] ?? totalSourceSeconds * 0.67) - 0.7,
  (zoneTimes[8] ?? totalSourceSeconds * 0.75) - 0.65,
  (zoneTimes[2] ?? totalSourceSeconds * 0.25) - 0.55,
  (zoneTimes[6] ?? totalSourceSeconds * 0.58) - 0.65,
  (zoneTimes[10] ?? totalSourceSeconds * 0.92) - 0.8,
  (zoneTimes[9] ?? totalSourceSeconds * 0.84) - 0.45,
  summitAt - 2.3,
];
const starts = anchors.map((anchor, index) =>
  clamp(anchor, 0, totalSourceSeconds - durations[index])
);

const generatedSource = `// Generated by scripts/prepare.mjs from the captured event timeline.\n` +
  `export const SOURCE_STARTS = ${JSON.stringify(starts.map(round), null, 2)} as const;\n` +
  `export const SOURCE_DURATION_SECONDS = ${round(totalSourceSeconds)};\n`;
await writeFile(path.join(videoDir, 'src', 'timings.generated.ts'), generatedSource);

process.stdout.write(
  `${JSON.stringify(
    {
      source: 'public/generated/gameplay.webm',
      sourceDurationSeconds: round(totalSourceSeconds),
      readyAt: round(readyAt),
      fallAt: round(fallAt),
      summitAt: round(summitAt),
      uniqueZones: zoneTimes.length,
      shotStarts: starts.map(round),
    },
    null,
    2
  )}\n`
);

function firstEvent(events, name) {
  return events.find((event) => event.name === name);
}

function uniqueZoneTimes(events) {
  const seen = new Set();
  const result = [];
  for (const event of events) {
    if (event.name !== 'zone') continue;
    const zone = event.detail?.zoneId ?? event.detail?.zone ?? event.detail?.name;
    if (!zone || seen.has(zone)) continue;
    seen.add(zone);
    result.push({ zone, at: event.at });
  }
  return result;
}

function seconds(milliseconds) {
  return Number(milliseconds) / 1000;
}

function clamp(value, minimum, maximum) {
  return Math.max(minimum, Math.min(maximum, value));
}

function round(value) {
  return Math.round(value * 1000) / 1000;
}
