// Generated by scripts/prepare.mjs from the captured event timeline.
export const SOURCE_STARTS = [
  0.127,
  10.578,
  13.928,
  27.195,
  0.427,
  39.878,
  52.461,
  66.344,
  79.462,
  92.878,
  105.743,
  119.043,
  39.178,
  92.978,
  145.759,
  132.876,
  155.374
] as const;
export const SOURCE_DURATION_SECONDS = 158.674;
